name: Patch Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment variables
      run: echo "PATCHVBMETAFLAG=true" >> $GITHUB_ENV
           sudo apt-get update && sudo apt-get install -y aria2 p7zip-full

    - name: Checkout
      uses: actions/checkout@v4.1.4

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with: 
         python-version: '3.12.3'
      
    - name: Load config variables
      id: config
      run: |
        cat config.env | xargs -n1 | while read line; do
          echo "Setting $line"
          echo "$line" >>$GITHUB_ENV
        done

    # 获取bmax121/kernelpatch仓库的最新tag标签
    - name: Get latest tag from bmax121/kernelpatch
      id: latest_tag_kernelpatch
      run: |
        # 使用GitHub API获取bmax121/kernelpatch的最新tag
        latest_tag_response=$(curl -s https://api.github.com/repos/bmax121/kernelpatch/tags)
        # 解析JSON响应以获取最新tag
        latest_tag=$(echo "$latest_tag_response" | grep -o '"name":.*' | head -n 1 | cut -d '"' -f 4)
        echo "Latest tag is: $latest_tag"
        # 设置输出变量
        echo "::set-output name=tag::$latest_tag"

    # 使用获取到的最新tag来设置下载链接
    - name: Set download URLs with latest tag from bmax121/kernelpatch
      run: |
        # 更新kptools-linux的下载链接
        echo "KP_TOOLS_URL=https://github.com/bmax121/KernelPatch/releases/download/${{ steps.latest_tag_kernelpatch.outputs.tag }}/kptools-linux" >>$GITHUB_ENV
        # 更新kpimg-android的下载链接
        echo "KP_IMG_URL=https://github.com/bmax121/KernelPatch/releases/download/${{ steps.latest_tag_kernelpatch.outputs.tag }}/kpimg-android" >>$GITHUB_ENV

    - name: Download files
      run: |
        aria2c -o magiskboot https://github.com/xiaoxindada/magiskboot_ndk_on_linux/releases/latest/download/magiskboot.7z
        aria2c -o kpimg-android $KP_IMG_URL
        aria2c -o kptools-linux $KP_TOOLS_URL
        7z magiskboot.7z
        
    - name: download boot
      uses: dawidd6/action-download-artifact@v3.1.4
      with:
        repo: liaoke01/BootIMGExtractAction
        workflow_conclusion: success
        workflow: BootIMGExtractAction.yml
            

    - name: Rename files
      run: |
        mv kptools-linux kptools
        mv kpimg-android kpimg
        chmod +x magiskboot kptools

    - name: Patch commands
      run: |
        ./magiskboot unpack boot.img
        mv kernel kernel.ori
        ./kptools -p -i kernel.ori -k kpimg -s $SKEY -o kernel
        ./magiskboot repack boot.img

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: new-boot.img
        path: new-boot.img
